import streamlit as st
import requests
import pandas as pd
from datetime import datetime
import re

# Page Configuration
st.set_page_config(
    page_title="Signature Aviation Live API & Fee Tracker",
    page_icon="✈",
    layout="wide"
)

st.title("✈️ Signature Aviation — Live FBO Service Fees Inspector")
st.markdown("Extracts and displays live handling, infrastructure, and auxiliary service fees using verified station base IDs.")

# Filtered (starts with 'K') and alphabetically sorted stations from locations_output.csv
ALL_STATIONS = {
    "KACY": {"baseId": "L27", "baseCode": "ACY"},
    "KAMA": {"baseId": "B82", "baseCode": "AMA"},
    "KAPA (B86)": {"baseId": "B86", "baseCode": "APA"},
    "KAPA (P66)": {"baseId": "P66", "baseCode": "APA"},
    "KATL": {"baseId": "L35", "baseCode": "ATL"},
    "KAUS": {"baseId": "P21", "baseCode": "AUS"},
    "KAVL": {"baseId": "L09", "baseCode": "AVL"},
    "KBCT": {"baseId": "P54", "baseCode": "BCT"},
    "KBDL": {"baseId": "P53", "baseCode": "BDL"},
    "KBED": {"baseId": "P74", "baseCode": "BED"},
    "KBFI": {"baseId": "L20", "baseCode": "BFI"},
    "KBFM": {"baseId": "P27", "baseCode": "BFM"},
    "KBJC": {"baseId": "L54", "baseCode": "BJC"},
    "KBKL": {"baseId": "L07", "baseCode": "BKL"},
    "KBNA": {"baseId": "V52", "baseCode": "BNA"},
    "KBOS": {"baseId": "V42", "baseCode": "BOS"},
    "KBTR": {"baseId": "L52", "baseCode": "BTR"},
    "KBUF": {"baseId": "B85", "baseCode": "BUF"},
    "KBWI": {"baseId": "B09", "baseCode": "BWI"},
    "KBZN": {"baseId": "P55", "baseCode": "BZN"},
    "KCHO": {"baseId": "L48", "baseCode": "CHO"},
    "KCHS": {"baseId": "L16", "baseCode": "CHS"},
    "KCID": {"baseId": "L36", "baseCode": "CID"},
    "KCMH": {"baseId": "L14", "baseCode": "CMH"},
    "KDAL (B84)": {"baseId": "B84", "baseCode": "DAL"},
    "KDAL (L45)": {"baseId": "L45", "baseCode": "DAL"},
    "KDAL (P63)": {"baseId": "P63", "baseCode": "DAL"},
    "KDAL (P82)": {"baseId": "P82", "baseCode": "DAL"},
    "KDCA": {"baseId": "B10", "baseCode": "DCA"},
    "KDEN": {"baseId": "P83", "baseCode": "DEN"},
    "KDJT (K60)": {"baseId": "K60", "baseCode": "DJT"},
    "KDJT (P61)": {"baseId": "P61", "baseCode": "DJT"},
    "KDSM": {"baseId": "V47", "baseCode": "DSM"},
    "KDTW": {"baseId": "P09", "baseCode": "DTW"},
    "KEFD": {"baseId": "L59", "baseCode": "EFD"},
    "KEGE": {"baseId": "P93", "baseCode": "EGE"},
    "KEWR": {"baseId": "B07", "baseCode": "EWR"},
    "KEYW": {"baseId": "L32", "baseCode": "EYW"},
    "KF45": {"baseId": "L31", "baseCode": "F45"},
    "KFAT": {"baseId": "P35", "baseCode": "FAT"},
    "KFAY": {"baseId": "L39", "baseCode": "FAY"},
    "KFDK": {"baseId": "L11", "baseCode": "FDK"},
    "KFLL": {"baseId": "P84", "baseCode": "FLL"},
    "KFOK": {"baseId": "P00", "baseCode": "FOK"},
    "KFSD": {"baseId": "L08", "baseCode": "FSD"},
    "KFSM": {"baseId": "B80", "baseCode": "FSM"},
    "KFTY": {"baseId": "I71", "baseCode": "FTY"},
    "KFXE": {"baseId": "B95", "baseCode": "FXE"},
    "KGEG": {"baseId": "L56", "baseCode": "GEG"},
    "KGRR": {"baseId": "L38", "baseCode": "GRR"},
    "KGSO": {"baseId": "L22", "baseCode": "GSO"},
    "KHOU": {"baseId": "I72", "baseCode": "HOU"},
    "KHPN (P57)": {"baseId": "P57", "baseCode": "HPN"},
    "KHPN (P60)": {"baseId": "P60", "baseCode": "HPN"},
    "KHSV": {"baseId": "P25", "baseCode": "HSV"},
    "KHWD": {"baseId": "I53", "baseCode": "HWD"},
    "KHXD": {"baseId": "P37", "baseCode": "HXD"},
    "KIAD": {"baseId": "P02", "baseCode": "IAD"},
    "KIAH": {"baseId": "L46", "baseCode": "IAH"},
    "KICT": {"baseId": "I75", "baseCode": "ICT"},
    "KIND": {"baseId": "P85", "baseCode": "IND"},
    "KINT": {"baseId": "L40", "baseCode": "INT"},
    "KISM": {"baseId": "I70", "baseCode": "ISM"},
    "KIXD": {"baseId": "G42", "baseCode": "IXD"},
    "KJAX": {"baseId": "P73", "baseCode": "JAX"},
    "KLAS": {"baseId": "H10", "baseCode": "LAS"},
    "KLAX": {"baseId": "L29", "baseCode": "LAX"},
    "KLEX": {"baseId": "B83", "baseCode": "LEX"},
    "KLFT": {"baseId": "L12", "baseCode": "LFT"},
    "KLGB": {"baseId": "P31", "baseCode": "LGB"},
    "KLIT": {"baseId": "B90", "baseCode": "LIT"},
    "KLRD": {"baseId": "L25", "baseCode": "LRD"},
    "KLUK": {"baseId": "L15", "baseCode": "LUK"},
    "KMAF": {"baseId": "L55", "baseCode": "MAF"},
    "KMCI": {"baseId": "G43", "baseCode": "MCI"},
    "KMCO": {"baseId": "P08", "baseCode": "MCO"},
    "KMDW": {"baseId": "B25", "baseCode": "MDW"},
    "KMEM": {"baseId": "P86", "baseCode": "MEM"},
    "KMHT": {"baseId": "P56", "baseCode": "MHT"},
    "KMIA": {"baseId": "L23", "baseCode": "MIA"},
    "KMKC": {"baseId": "G41", "baseCode": "MKC"},
    "KMKE": {"baseId": "V50", "baseCode": "MKE"},
    "KMMU": {"baseId": "P67", "baseCode": "MMU"},
    "KMOB": {"baseId": "P26", "baseCode": "MOB"},
    "KMQS": {"baseId": "L53", "baseCode": "MQS"},
    "KMSP": {"baseId": "V51", "baseCode": "MSP"},
    "KMSY": {"baseId": "P36", "baseCode": "MSY"},
    "KNEW": {"baseId": "L13", "baseCode": "NEW"},
    "KOAK": {"baseId": "L30", "baseCode": "OAK"},
    "KOMA": {"baseId": "P44", "baseCode": "OMA"},
    "KOPF": {"baseId": "L26", "baseCode": "OPF"},
    "KORD": {"baseId": "B21", "baseCode": "ORD"},
    "KORF": {"baseId": "L50", "baseCode": "ORF"},
    "KPDK": {"baseId": "P65", "baseCode": "PDK"},
    "KPHK": {"baseId": "L33", "baseCode": "PHK"},
    "KPIE": {"baseId": "P11", "baseCode": "PI